---
- name: Update repository Centos
  hosts: myhost
  become: true

  vars:
    proxy_env:
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"

  tasks:
    - name: install mysql server
      yum:
        name: mysql-server
        state: latest
      environment: "{{ proxy_env }}" 
    
    - name: enable service mysql
      service:
        name: mysqld.service
        enabled: yes

    - name: starts service mysql
      service:
        name: mysqld.service
        state: started
