---
- name: Update repository Centos
  hosts: myhost
  become: true

  vars:
    proxy_env:
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"

  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      environment: "{{ proxy_env }}"

    - name: install mysql server
      yum:
        name: mysql-server
        state: latest
      environment: "{{ proxy_env }}" 
    